/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 345700744
 */
public class learningPage extends javax.swing.JFrame {
    private Learn learn;
    private Bookmark bookmarks;

    /**
     * Creates new form learningPage
     */
    public learningPage() {
        initComponents();
        learn = new Learn();
        bookmarks = new Bookmark();
        learn.loadInformation("informations.txt");
        updateBookmarkList();
        learn.setIndex(0);
        textBox.setText(learn.getSection(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookmark = new javax.swing.JFrame();
        bookmarkComboBox = new javax.swing.JComboBox<>();
        removeButton = new javax.swing.JButton();
        save = new javax.swing.JFrame();
        bookmarkNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saveButton2 = new javax.swing.JButton();
        saveButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBox = new javax.swing.JTextPane();
        nextButton = new javax.swing.JButton();
        bookmarkButton = new javax.swing.JButton();

        bookmark.setMinimumSize(new java.awt.Dimension(320, 110));
        bookmark.setPreferredSize(new java.awt.Dimension(320, 110));

        bookmarkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarkComboBoxActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookmarkLayout = new javax.swing.GroupLayout(bookmark.getContentPane());
        bookmark.getContentPane().setLayout(bookmarkLayout);
        bookmarkLayout.setHorizontalGroup(
            bookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookmarkLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bookmarkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        bookmarkLayout.setVerticalGroup(
            bookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookmarkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookmarkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        save.setMinimumSize(new java.awt.Dimension(307, 100));
        save.setPreferredSize(new java.awt.Dimension(307, 100));

        jLabel3.setText("Name");

        saveButton2.setText("Save");
        saveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveLayout = new javax.swing.GroupLayout(save.getContentPane());
        save.getContentPane().setLayout(saveLayout);
        saveLayout.setHorizontalGroup(
            saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveLayout.createSequentialGroup()
                        .addComponent(bookmarkNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton2))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saveLayout.setVerticalGroup(
            saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookmarkNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton2))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saveButton1.setText("Save");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        textBox.setEditable(false);
        textBox.setAutoscrolls(false);
        jScrollPane1.setViewportView(textBox);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        bookmarkButton.setText("Bookmark");
        bookmarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookmarkButton)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookmarkButton)
                    .addComponent(saveButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateBookmarkList() {
        bookmarkComboBox.removeAllItems();
        String[] bookmarkNames = bookmarks.getBookmarkNames();

        if (bookmarkNames.length == 0) {
            bookmarkComboBox.addItem("No bookmarks available");
        } else {
            for (String name : bookmarkNames) {
                bookmarkComboBox.addItem(name);
            }
        }
        bookmarkComboBox.setSelectedIndex(-1);
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        learn.loadInformation("informations.txt");
        String informations = learn.getNextSection();
        textBox.setText(informations);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void bookmarkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarkComboBoxActionPerformed
        if (bookmarkComboBox.getSelectedIndex() > -1) {
            String selectedBookmark = bookmarkComboBox.getSelectedItem().toString().trim();
            int sectionIndex = bookmarks.getBookmarkIndex(selectedBookmark);
            if (sectionIndex >= 0 && sectionIndex < learn.loadInformation("informations.txt").length) { 
                learn.setIndex(sectionIndex); 
                textBox.setText(learn.getSection(sectionIndex));
            } else {
                System.out.println("Error: Invalid index.");
            }
        }
    }//GEN-LAST:event_bookmarkComboBoxActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (bookmarkComboBox.getSelectedItem() != null) {
            String name = bookmarkComboBox.getSelectedItem().toString();
            if (!name.equals("No bookmarks available")) {
                bookmarks.removeBookmark(name.trim());
                updateBookmarkList();
            } else {
                System.out.println("No valid bookmark selected.");
            }
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void saveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton2ActionPerformed
        String name = bookmarkNameField.getText().trim();
        int sectionIndex = learn.getIndex();
        if (!name.isEmpty()) {
            bookmarks.saveBookmark(name, sectionIndex);
            updateBookmarkList();
            textBox.setText(learn.getSection(sectionIndex));
            save.dispose();
        }
    }//GEN-LAST:event_saveButton2ActionPerformed

    private void bookmarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarkButtonActionPerformed
        int currentIndex = learn.getIndex();
        bookmarks.loadBookmarks();
        updateBookmarkList();
        if (currentIndex >= 0 && currentIndex < learn.loadInformation("informations.txt").length) {
            textBox.setText(learn.getSection(currentIndex)); 
        } else {
            System.out.println("Invalid index detected.");
        }
        bookmark.setVisible(true);
    }//GEN-LAST:event_bookmarkButtonActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        save.setVisible(true);
        bookmarkNameField.setText("");
    }//GEN-LAST:event_saveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(learningPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(learningPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(learningPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(learningPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new learningPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame bookmark;
    private javax.swing.JButton bookmarkButton;
    private javax.swing.JComboBox<String> bookmarkComboBox;
    private javax.swing.JTextField bookmarkNameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JFrame save;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton saveButton2;
    private javax.swing.JTextPane textBox;
    // End of variables declaration//GEN-END:variables
}

